### ISSUE TITLE
0.12 t/readwrite.t hang on Windows

### ISSUE THREAD

**Issue by mrmuskrat** [gittex/File-Blarf#1]
I found that one of my smokers was stuck on this module so I tried it manually to see where it hung up. This is Strawberry Perl 5.12.3 on Windows 7.

	C:\Users\mmusgrove\Desktop>cpan

	There seems to be running another CPAN process (pid 11844).  Contacting...
	Other job not responding. Shall I overwrite the lockfile 'C:\strawberry\cpan\.lo
	ck'? (Y/n) [y] y

	cpan shell -- CPAN exploration and modules installation (v1.9800)
	Enter 'h' for help.

	cpan> look File::Blarf
	Database was generated on Thu, 07 Feb 2013 08:09:55 GMT
	Running look for module 'File::Blarf'

	Trying to open a subshell in the build directory...
	Checksum for C:\strawberry\cpan\sources\authors\id\T\TE\TEX\File-Blarf-0.12.tar.
	gz ok
	Scanning cache C:\strawberry\cpan\build for sizes
	............................................................................DONE

	Working directory is C:\strawberry\cpan\build\File-Blarf-0.12-tpSXrE
	Microsoft Windows [Version 6.1.7601]
	Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

	C:\strawberry\cpan\build\File-Blarf-0.12-tpSXrE>perl Makefile.PL
	Checking if your kit is complete...
	Looks good
	Writing Makefile for File::Blarf
	Writing MYMETA.yml and MYMETA.json

	C:\strawberry\cpan\build\File-Blarf-0.12-tpSXrE>dmake
	cp lib/File/Blarf.pm blib\lib\File\Blarf.pm

	C:\strawberry\cpan\build\File-Blarf-0.12-tpSXrE>dmake test
	C:\strawberry\perl\bin\perl.exe "-MExtUtils::Command::MM" "-e" "test_harness(0,
	'blib\lib', 'blib\arch')" t/*.t
	t/00-load.t ............. # Testing File::Blarf 0.12, Perl 5.012003, C:\strawber
	ry\perl\bin\perl.exe
	t/00-load.t ............. ok
	t/manifest.t ............ skipped: Author tests not required for installation
	t/pod-coverage.t ........ ok
	t/pod.t ................. ok
	t/readwrite.t ........... 1/11

**Comment by vytas-dauksa** [comment]
Hi, as part of CPAN Pull Request Challenge 2015 ( http://neilb.org/2014/11/29/pr-challenge-2015.html ) I was assigned to make a pull request to File::Blarf module. As this is the only opened issue, I will try to solve it.

**Comment by dominikschulz** [comment]
Merged. Thanks!
